### ISSUE TITLE
Server crashing on Linux

### ISSUE THREAD

**Issue by awillinger** [peace-maker/sourcetvmanager#2]
Decided to look into this issue again and saw that this repo has issues enabled.
Calling SourceTV_IsRecording() on a linux based gameserver (both Debian 7 & 8) causes the server to crash immediately.

Crashlog:

```
----------------------------------------------
CRASH: Fri Sep 30 20:34:55 CEST 2016
Start Line: ./srcds_linux -game csgo -usercon -ip <redacted> -port <redacted> +game_type 0 +game_mode 0 +mapgroup mg_bhop +map bhop_forest -maxplayers_override 10 +sv_hibernate_when_empty 0 -debug +bot_quota 0 -tickrate 102.4
[New LWP 11961]
[New LWP 11964]
[New LWP 11962]
[New LWP 11972]
[New LWP 11967]
[New LWP 11973]
[New LWP 11965]
[New LWP 11982]
[New LWP 11970]
[New LWP 11989]
[New LWP 11974]
[New LWP 11975]
[New LWP 11977]
[New LWP 11981]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./srcds_linux -game csgo -usercon -ip <redacted> -port <redacted> +game_type 0 +ga'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xe5bfbc5a in Native_IsRecording (pContext=0xc3fb0c0, params=0xc68d16c) at /home/jannik/git/sourcetvmanager/natives.cpp:463
#0  0xe5bfbc5a in Native_IsRecording (pContext=0xc3fb0c0, params=0xc68d16c) at /home/jannik/git/sourcetvmanager/natives.cpp:463
#1  0xe3f03421 in ?? ()
#2  0xe3f03421 in ?? ()
#3  0xe3f0330e in ?? ()
#4  0xec78f06f in ?? ()
#5  0xece12045 in sp::Environment::Invoke(sp::PluginRuntime*, sp::CompiledFunction*, int*) () from /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/bin/sourcepawn.jit.x86.so
#6  0xece14955 in sp::InvokeFrame::InvokeFrame(sp::PluginContext*, unsigned int) () from /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/bin/sourcepawn.jit.x86.so
#7  0xece183a0 in sp::PluginContext::Invoke(unsigned int, int const*, unsigned int, int*) () from /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/bin/sourcepawn.jit.x86.so
#8  0x000000df in ?? ()
#9  0x0a5f3090 in ?? ()
#10 0x0a5fff58 in ?? ()
pContext = 0xc3fb0c0
params = 0xc68d16c
eax            0xcc6ee50        214363728
ecx            0x5ed0   24272
edx            0x0      0
ebx            0xc68d170        208195952
esp            0xffb40750       0xffb40750
ebp            0xffb40788       0xffb40788
esi            0xc6872a0        208171680
edi            0x5ecc   24268
eip            0xe5bfbc5a       0xe5bfbc5a <Native_IsRecording(SourcePawn::IPluginContext*, cell_t const*)+42>
eflags         0x10206  [ PF IF RF ]
cs             0x23     35
ss             0x2b     43
ds             0x2b     43
es             0x2b     43
fs             0x0      0
gs             0x63     99
From        To          Syms Read   Shared Object Library
                        No          linux-gate.so.1
0xf7764600  0xf7791ed5  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libm.so.6
0xf775bad0  0xf775c96c  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libdl.so.2
0xf7742870  0xf774ef87  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
0xf75a8420  0xf76d891e  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libc.so.6
0xf77b5860  0xf77cd0fc  Yes (*)     /lib/ld-linux.so.2
0xf7550030  0xf756c618  Yes (*)     /gameserver/csgo/setup_bhop/bin/libtier0.so
0xf74f9f30  0xf7523dbc  Yes (*)     /gameserver/csgo/setup_bhop/bin/libvstdlib.so
0xf7007ba0  0xf708ef98  Yes (*)     /gameserver/csgo/setup_bhop/bin/dedicated.so
0xf6fc9d60  0xf6fdf1b4  Yes (*)     /gameserver/csgo/setup_bhop/bin/libsteam_api.so
0xf6f2d914  0xf6f73c78  Yes         /gameserver/csgo/setup_bhop/bin/libstdc++.so.6
0xf6ed3e04  0xf6ee34b8  Yes         /gameserver/csgo/setup_bhop/bin/libgcc_s.so.1
0xf5fe93b0  0xf642e5b0  Yes (*)     /gameserver/csgo/setup_bhop/bin/engine.so
0xf58851a0  0xf5964e7c  Yes (*)     /gameserver/csgo/setup_bhop/bin/materialsystem.so
0xf531d8a0  0xf53d263c  Yes (*)     /gameserver/csgo/setup_bhop/bin/studiorender.so
0xf512a4e0  0xf5282dec  Yes (*)     /gameserver/csgo/setup_bhop/bin/vphysics.so
0xf501d3d0  0xf509a554  Yes (*)     /gameserver/csgo/setup_bhop/bin/datacache.so
0xf4f49d40  0xf4fc05e4  Yes (*)     /gameserver/csgo/setup_bhop/bin/vscript.so
0xf4f09bd0  0xf4f215d0  Yes (*)     /gameserver/csgo/setup_bhop/bin/shaderapiempty.so
0xf36824c0  0xf42f8b04  Yes (*)     /home/csgo/.steam/sdk32/steamclient.so
0xf77a79b0  0xf77aaeaa  Yes (*)     /lib/i386-linux-gnu/i686/cmov/librt.so.1
0xf3121eb0  0xf3177d48  Yes (*)     /gameserver/csgo/setup_bhop/csgo/bin/matchmaking_ds.so
0xf2128ca0  0xf2ace2f4  Yes (*)     /gameserver/csgo/setup_bhop/csgo/bin/server.so
0xf1dbf3d0  0xf1debbb4  Yes (*)     /gameserver/csgo/setup_bhop/bin/soundemittersystem.so
0xf1d8bf40  0xf1da26bc  Yes (*)     /gameserver/csgo/setup_bhop/bin/scenefilecache.so
0xedb6c130  0xedb6de0c  Yes (*)     /gameserver/csgo/setup_bhop/csgo/../csgo/addons/metamod/bin/server.so
0xedb394b0  0xedb5fe78  Yes (*)     /gameserver/csgo/setup_bhop/csgo/../csgo/addons/metamod/bin/metamod.2.csgo.so
0xedb26a90  0xedb271c8  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/bin/sourcemod_mm_i486.so
0xecb13c80  0xecc810f9  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/bin/sourcemod.2.csgo.so
0xece4b430  0xecea00a0  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/bin/sourcemod.logic.so
0xece11700  0xece2f2a4  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/bin/sourcepawn.jit.x86.so
0xedb214f0  0xedb24334  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/updater.ext.so
0xec75fa60  0xec787df5  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/webternet.ext.so
0xedb1e790  0xedb1ecc4  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/stripper/bin/stripper_mm_i486.so
0xeb736f20  0xeb74d790  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/stripper/bin/stripper.16.csgo.so
0xedb04280  0xedb18ed4  Yes (*)     /gameserver/csgo/setup_bhop/csgo/+stripper_path/bin/stripper.core.so
0xeb717ad0  0xeb71e8ab  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libnss_files.so.2
0xece02c40  0xece05bce  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libnss_dns.so.2
0xeb5eb720  0xeb5f7ce4  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libresolv.so.2
0xeb728d40  0xeb72a778  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/cleaner.ext.2.csgo.so
0xeb458ac0  0xeb598c80  Yes         /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/curl.ext.so
0xeb389f60  0xeb3b54a8  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/accelerator.ext.so
0xeb70d800  0xeb71319d  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/game.cstrike.ext.2.csgo.so
0xeb705c90  0xeb7094d8  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/bintools.ext.so
0xeab1cde0  0xeab53d82  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/sdktools.ext.2.csgo.so
0xeab06780  0xeab0ce78  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/topmenus.ext.so
0xea9f8ae0  0xea9fd634  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/clientprefs.ext.so
0xea8cbe00  0xea9ebf00  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/dbi.sqlite.ext.so
0xe9c051b0  0xe9c23e52  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/sdkhooks.ext.2.csgo.so
0xe9b0e410  0xe9bcaaa4  Yes         /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/socket.ext.so
0xe928d930  0xe9297404  Yes         /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/dhooks.ext.so
0xea002e30  0xea005698  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/geoip.ext.so
0xe888d320  0xe88bf4d0  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/regex.ext.so
0xe82b5490  0xe83401f5  Yes (*)     /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/dbi.mysql.ext.so
0xe92128f0  0xe9223122  Yes (*)     /lib/i386-linux-gnu/libz.so.1
0xe5bf8510  0xe5d1e433  Yes         /gameserver/csgo/setup_bhop/csgo/addons/sourcemod/extensions/sourcetvmanager.ext.2.csgo.so
(*): Shared library is missing debugging information.
Dump of assembler code for function Native_IsRecording(SourcePawn::IPluginContext*, cell_t const*):
   0xe5bfbc30 <+0>:     mov    0xe5da5640,%eax
   0xe5bfbc35 <+5>:     test   %eax,%eax
   0xe5bfbc37 <+7>:     je     0xe5bfbc68 <Native_IsRecording(SourcePawn::IPluginContext*, cell_t const*)+56>
   0xe5bfbc39 <+9>:     sub    $0x1c,%esp
   0xe5bfbc3c <+12>:    mov    %eax,(%esp)
   0xe5bfbc3f <+15>:    call   0xe5c00e00 <HLTVServerWrapper::GetDemoRecorder()>
   0xe5bfbc44 <+20>:    test   %eax,%eax
   0xe5bfbc46 <+22>:    je     0xe5bfbc70 <Native_IsRecording(SourcePawn::IPluginContext*, cell_t const*)+64>
   0xe5bfbc48 <+24>:    mov    0xe5da5640,%eax
   0xe5bfbc4d <+29>:    mov    %eax,(%esp)
   0xe5bfbc50 <+32>:    call   0xe5c00e00 <HLTVServerWrapper::GetDemoRecorder()>
   0xe5bfbc55 <+37>:    mov    (%eax),%edx
   0xe5bfbc57 <+39>:    mov    %eax,(%esp)
=> 0xe5bfbc5a <+42>:    call   *0x28(%edx)
   0xe5bfbc5d <+45>:    add    $0x1c,%esp
   0xe5bfbc60 <+48>:    movzbl %al,%eax
   0xe5bfbc63 <+51>:    ret
   0xe5bfbc64 <+52>:    lea    0x0(%esi,%eiz,1),%esi
   0xe5bfbc68 <+56>:    xor    %eax,%eax
   0xe5bfbc6a <+58>:    ret
   0xe5bfbc6b <+59>:    nop
   0xe5bfbc6c <+60>:    lea    0x0(%esi,%eiz,1),%esi
   0xe5bfbc70 <+64>:    xor    %eax,%eax
   0xe5bfbc72 <+66>:    add    $0x1c,%esp
   0xe5bfbc75 <+69>:    ret
End of assembler dump.
Stack level 0, frame at 0xffb40770:
 eip = 0xe5bfbc5a in Native_IsRecording (/home/jannik/git/sourcetvmanager/natives.cpp:463); saved eip = 0xe3f03421
 called by frame at 0xffb40790
 source language c++.
 Arglist at 0xffb4074c, args: pContext=0xc3fb0c0, params=0xc68d16c
 Locals at 0xffb4074c, Previous frame's sp is 0xffb40770
 Saved registers:
  eip at 0xffb4076c
End of Source crash report
----------------------------------------------
```
edx is null, which means that either the hltv instance is null (unlikely), or the offset is incorrect. Unfortunately, I am not as good in reversing, hence why my analysis is a bit limited.
Also tried changing around the "read" value for CHLTVServer::m_DemoRecorder between 1-14, but it still crashes (method ends after that).

If you need any additional information, feel free to ask!
Thanks

**Comment by peace-maker** [comment]
This was fixed in v1.0.3 now
